# Generated by Django 6.0.1 on 2026-02-26 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invited_members',
            field=models.ManyToManyField(related_name='invited_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
