# Generated by Django 6.0.1 on 2026-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_team_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('details', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('location', models.CharField()),
                ('image', models.ImageField(default='uploaded_media/events/events_icon.svg', upload_to='uploaded_media/events')),
            ],
        ),
    ]
