# Generated by Django 6.0.1 on 2026-02-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
