# Generated by Django 6.0.1 on 2026-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
