# Generated by Django 6.0.1 on 2026-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_event_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_tab',
            field=models.BooleanField(default=True, verbose_name='Open registration link in new tab?'),
        ),
    ]
