# Generated by Django 6.0.1 on 2026-03-17 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_event_new_tab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_registered', 'User Registered'), ('user_deleted', 'User Deleted'), ('role_changed', 'Role Changed'), ('event_created', 'Event Created'), ('event_edited', 'Event Edited'), ('event_deleted', 'Event Deleted'), ('team_created', 'Team Created'), ('team_edited', 'Team Edited'), ('team_deleted', 'Team Deleted'), ('member_joined', 'Member Joined Team'), ('member_left', 'Member Left Team'), ('workshop_created', 'Workshop Created'), ('workshop_edited', 'Workshop Edited'), ('workshop_deleted', 'Workshop Deleted'), ('workshop_published', 'Workshop Published'), ('workshop_archived', 'Workshop Archived')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('Presentation', 'Presentation'), ('Document', 'Document'), ('Video', 'Video')], default='Document', max_length=20)),
                ('module', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workshops/')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation'), ('video', 'Video'), ('resource', 'Resource')], default='document', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='website.workshop')),
            ],
        ),
    ]
