# Generated by Django 6.0.1 on 2026-01-31 12:56

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=-2008),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=django_countries.fields.CountryField(default='SY', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_of_graduation',
            field=models.CharField(default=2030),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.majors'),
            preserve_default=False,
        ),
    ]
