# Generated by Django 6.0.1 on 2026-02-01 13:04

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_date_of_birth_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='graduation_year',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.majors'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
