# Generated by Django 6.0.1 on 2026-02-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_member_date_joined'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Majors',
            new_name='Major',
        ),
    ]
