# Generated by Django 6.0.1 on 2026-02-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_majors_major'),
        ('accounts', '0007_remove_emailotp_user_emailotp_email'),
    ]

    operations = [
    ]
